<?php include ('header.php'); ?>
<?php
// Retrieve the book title from the URL parameter
$book_title = isset($_GET['title']) ? $_GET['title'] : '';
?>


<script>
function showBookDetails() {
    var bookTitleInput = document.getElementById("first-name2");
    var bookDetailsDiv = document.getElementById("bookDetails");
    
    if (bookTitleInput.value !== "") {
        bookDetailsDiv.style.display = "block";
        var numberOfBooks = parseInt(bookTitleInput.value);
        var bookDetailsFields = document.getElementById("bookDetailsFields");

        // Clear previous fields
        bookDetailsFields.innerHTML = '';

        // Create new fields
        for (var i = 0; i < numberOfBooks; i++) {
            var row = document.createElement("div");
            row.className = "row";

            // Book Title
            var titleCol = document.createElement("div");
            titleCol.className = "col-md-3 form-group";

            var titleLabel = document.createElement("label");
            titleLabel.className = "control-label";
            titleLabel.textContent = "Book Title:";
            titleCol.appendChild(titleLabel);

            var titleInput = document.createElement("input");
            titleInput.type = "text";
            titleInput.value = "<?php echo $book_title; ?>";
            titleInput.name = "book_titles[]";
            titleInput.className = "form-control";
            titleInput.readOnly = true;
            titleCol.appendChild(titleInput);

            // ISBN (Autogenerated)
            var isbnCol = document.createElement("div");
            isbnCol.className = "col-md-3 form-group";

            var isbnLabel = document.createElement("label");
            isbnLabel.className = "control-label";
            isbnLabel.textContent = "ISBN:";
            isbnCol.appendChild(isbnLabel);

            var isbnInput = document.createElement("input");
            isbnInput.type = "text";
            isbnInput.value = generateISBN();
            isbnInput.name = "isbns[]";
            isbnInput.className = "form-control";
            isbnInput.readOnly = true;
            isbnCol.appendChild(isbnInput);

            // Edition (Copies)
            var editionCol = document.createElement("div");
            editionCol.className = "col-md-2 form-group";

            var editionLabel = document.createElement("label");
            editionLabel.className = "control-label";
            editionLabel.textContent = "Edition:";
            editionCol.appendChild(editionLabel);

            var editionSelect = document.createElement("select");
            editionSelect.name = "editions[]";
            editionSelect.className = "form-control";
            editionSelect.required = true;

            // Add options from 2000 to 2024
            for (var j = 2000; j <= 2024; j++) {
                var option = document.createElement("option");
                option.value = j;
                option.textContent = j;
                editionSelect.appendChild(option);
            }

            editionCol.appendChild(editionSelect);

            // Copies
            var copiesCol = document.createElement("div");
            copiesCol.className = "col-md-2 form-group";

            var copiesLabel = document.createElement("label");
            copiesLabel.className = "control-label";
            copiesLabel.textContent = "Copies:";
            copiesCol.appendChild(copiesLabel);

            var copiesInput = document.createElement("input");
            copiesInput.type = "number";
            copiesInput.value = 1; // Default value for copies
            copiesInput.name = "copies[]";
            copiesInput.className = "form-control";
            copiesCol.appendChild(copiesInput);

            // Status
            var statusCol = document.createElement("div");
            statusCol.className = "col-md-2 form-group";

            var statusLabel = document.createElement("label");
            statusLabel.className = "control-label";
            statusLabel.textContent = "Status:";
            statusCol.appendChild(statusLabel);

            var statusSelect = document.createElement("select");
            statusSelect.name = "statuses[]";
            statusSelect.className = "select2_single form-control";
            statusSelect.setAttribute("tabindex", "-1");
            statusSelect.required = true;

            var statusOptions = ["New", "Old", "Lost", "Damaged", "Replacement", "Hardbound"];
            for (var k = 0; k < statusOptions.length; k++) {
                var option = document.createElement("option");
                option.value = statusOptions[k];
                option.textContent = statusOptions[k];
                statusSelect.appendChild(option);
            }

            statusCol.appendChild(statusSelect);

            row.appendChild(titleCol);
            row.appendChild(isbnCol);
            row.appendChild(editionCol);
            row.appendChild(copiesCol);
            row.appendChild(statusCol);

            bookDetailsFields.appendChild(row);
        }
    } else {
        bookDetailsDiv.style.display = "none";
    }
}

function generateISBN() {
    var isbn = '';
    for (var i = 0; i < 13; i++) {
        isbn += Math.floor(Math.random() * 10);
    }
    return isbn;
}
</script>

<div class="page-title">
    <div class="title_left">
        <h3>
            <small>Home / Books /</small> Book Details
        </h3>
    </div>
</div>
<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-plus"></i> Book Details</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <?php
// Retrieve the book title from the URL parameter
$book_title = isset($_GET['title']) ? $_GET['title'] : '';
echo $book_title;
?>
                    
            <div class="x_content">
                <!-- content starts here -->
                <form method="post" action="store_book_details.php" enctype="multipart/form-data" class="form-horizontal form-label-left">
                    <input type="hidden" name="new_barcode" value="<?php echo $new_barcode; ?>">
                    
                    <div class="form-group">
                        <label class="control-label col-md-4" for="first-name">Enter No of Books<span class="required" style="color:red;">*</span>
                        </label>
                        <div class="col-md-4">
                            <input type="text" name="book_title" id="first-name2" required="required" class="form-control col-md-7 col-xs-12" oninput="showBookDetails()">
                        </div>
                    </div>
                    
                    <div id="bookDetails" style="display: none;">
                        <div id="bookDetailsFields">
                            <!-- Book details fields will be dynamically added here -->
                        </div>
                    </div>
                   
                    <!-- Other form fields go here -->
                    
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <a href="book.php"><button type="button" class="btn btn-primary"><i class="fa fa-times-circle-o"></i> Cancel</button></a>
                            <button type="submit" name="submit" class="btn btn-success"><i class="fa fa-plus-square"></i> Submit</button>
                        </div>
                    </div>
                </form>
                <!-- content ends here -->
            </div>
        </div>
    </div>
</div>

<?php include ('footer.php'); ?>
